# Generated by Django 5.0 on 2023-12-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_pdffile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(default='Write the body here', max_length=1000)),
                ('quote', models.CharField(default='Motivate with a related quote', max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('blog_image', models.ImageField(upload_to='blogImages')),
            ],
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='category',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdffile',
            name='cover_page',
            field=models.ImageField(default=1, upload_to='covers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdffile',
            name='department',
            field=models.CharField(choices=[('Electrical Department', 'Electrical Department'), ('Computer Department', 'Computer Department')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdffile',
            name='type',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('TEMPLATE', 'Template')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdffile',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
