# Generated by Django 5.0 on 2024-01-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
